SELECT TOP (1000) [order_number_sk]
      ,[order_number_pk]
      ,[retailer_name]
      ,[order_date]
      ,[order_day]
      ,[order_month]
      ,[order_year]
      ,[order_detail_code]
      ,[order_detail_product_number]
      ,[order_detail_quantity]
      ,[order_detail_unit_cost]
      ,[order_detail_unit_price]
      ,[order_detail_unit_sale_price]
      ,[return_code]
      ,[return_date]
      ,[return_reason_code]
      ,[return_quantity]
      ,[order_method_code]
      ,[sales_branch_code]
      ,[retailer_site_code]
      ,[sales_staff_code_fk]
      ,[sales_staff_code_fsk]
      ,[tstamp]
  FROM [greatoutdoors].[dbo].[orders]
  WHERE order_number_pk = 9479