SELECT TOP (1000) [SALES_STAFF_CODE_PK]
      ,[FIRST_NAME]
      ,[LAST_NAME]
      ,[POSITION_EN]
      ,[WORK_PHONE]
      ,[EXTENSION]
      ,[FAX]
      ,[EMAIL]
      ,[DATE_HIRED_DATE]
      ,[SALES_BRANCH_CODE]
      ,[MANAGER_CODE]
      ,[timestmp]
      ,[SALES_STAFF_CODE_SK]
  FROM [greatoutdoors].[dbo].[sales_staff]
  WHERE SALES_STAFF_CODE_PK = 27